version: '3.9'
services:
  challenge:
    build: joalvarezdev/joalvarez
    ports:
      - '8090:8090'
    links:
      - psqldata
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - APP_PORT=${APP_PORT}
  psqldata:
    image: postgres:15
    container_name: psqldata
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: