CREATE TABLE IF NOT EXISTS products (
	id UUID NOT NULL,
	name VARCHAR(100) NOT NULL,
	price DOUBLE PRECISION NOT NULL,
	stock INTEGER NOT NULL,
	active BOOLEAN NOT NULL DEFAULT TRUE,
	CONSTRAINT "pk_products" PRIMARY KEY (id)
);